version: '3'
services:
  restaurant-review:
    image: 'restaurant-review:latest'
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: restaurant-review
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

    networks:
      - spring-cloud-network

  database:
    image: 'postgres:latest'
    container_name: database
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - spring-cloud-network

networks:
  spring-cloud-network:
    driver: bridge